---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.storageClass.name }}
provisioner: {{ .Values.storage.storageClass.provisioner }}
parameters:
  containerName: {{ .Values.storage.storageClass.containerName }}
  storageAccount: {{ .Values.storage.storageClass.storageAccount }}
  protocol: {{ .Values.storage.storageClass.protocol }}
reclaimPolicy: {{ .Values.storage.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storage.storageClass.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storage.storageClass.allowVolumeExpansion }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvc.name }}
spec:
  accessModes:
    - {{ .Values.storage.pvc.accessMode }}
  storageClassName: {{ .Values.storage.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
