namespace: default

head:
  name: head
  image:
    repository: rayproject/ray
    tag: 2.9.3-py310
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "2"
      memory: "4Gi"
  volumeMount:
    mountPath: /models/llms
    pvcName: model-pvc

worker:
  name: worker
  replicas: 1
  image:
    repository: rayproject/ray
    tag: 2.9.3-py310
    pullPolicy: IfNotPresent
  resources:
    limits:
      gpu: 1
      cpu: "4"
      memory: "16Gi"
    requests:
      gpu: 1
      cpu: "4"
      memory: "16Gi"
  rayHeadHost: head
  rayHeadPort: "10001"
  volumeMount:
    mountPath: /models/llms
    pvcName: model-pvc

api:
  name: vllm-api
  replicas: 1
  image: vllm/vllm-openai:latest
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      gpu: 1
      cpu: "4"
      memory: "16Gi"
    requests:
      gpu: 1
      cpu: "4"
      memory: "16Gi"
  rayHeadAddress: head.default.svc.cluster.local:6379
  numCpus: 4
  sleepSeconds: 5
  modelBasePath: /models/llms
  modelName: mistral-7b/e0bc86c23ce5aae1db576c
  vllmArgs:
    - "--tensor-parallel-size=1"
    - "--max-num-seqs=64"
    - "--dtype=float16"
    - "--disable-log-requests"
  volumeMount:
    mountPath: /models/llms
    pvcName: model-pvc

storage:
  storageClass:
    name: model-blob
    provisioner: blob.csi.azure.com
    containerName: models
    storageAccount: mystorageaccount
    protocol: fuse
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
  pvc:
    name: model-pvc
    accessMode: ReadWriteMany
    storageClassName: model-blob
    size: 100Gi

