apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-head
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-head
  template:
    metadata:
      labels:
        app: vllm-head
    spec:
      nodeSelector:
            workload: rayHead
            #kubernetes.azure.com/scalesetpriority: spot
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: vllm-head
          image: vllm/vllm-openai:v0.8.2
          command: ["/bin/bash", "-c"]
          args:
            - pip install ray[client]==2.47.1 && pip install ray[default]==2.47.1 && ray start --head --port=6379 --ray-client-server-port=10001 --block --num-cpus 0
          ports:
            - containerPort: 6379
            - containerPort: 10001
          resources:
            requests:
              cpu: "500m"
              memory: "2500Mi"
            limits:
              cpu: "500m"
              memory: "2500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-head
spec:
  selector:
    app: vllm-head
  ports:
    - port: 6379
      targetPort: 6379
      name: ray-node
    - port: 10001
      targetPort: 10001
      name: ray-client
  type: ClusterIP

