apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-worker
  template:
    metadata:
      labels:
        app: vllm-worker
    spec:
      nodeSelector:
          workload: rayWorker
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: vllm-worker
          image: vllm/vllm-openai:v0.8.2
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - ray status 2>/dev/null | grep -i active || exit 1
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - ray status 2>/dev/null | grep -i active  || exit 1
            initialDelaySeconds: 180
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 10
          command: ["/bin/bash", "-c"]
          args:
            - pip install ray[client]==2.47.1  && pip install --upgrade transformers && ray start --address=vllm-head.default.svc.cluster.local:6379 --block --num-cpus 4
          resources:
            requests:
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          #resources:
          #  requests:
          #    cpu: "2000m"
          #    memory: "4500Mi"
          #  limits:
          #    cpu: "2000m"
          #    memory: "4500Mi"
          volumeMounts:
            - name: hf-cache
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
            - name: blob-models
              mountPath: /models/llms
              readOnly: true
      volumes:
        - name: hf-cache
          emptyDir: {}
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 15Gi
        - name: blob-models
          persistentVolumeClaim:
            claimName: azure-blob-model-pvc
