apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vllm-worker
  template:
    metadata:
      labels:
        app: vllm-worker
    spec:
      nodeSelector:
          workload: rayWorker
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
        - name: vllm-worker
          image: vllm/vllm-openai:latest
          command: ["/bin/bash", "-c"]
          args:
            - ray start --address=vllm-head.default.svc.cluster.local:6379 --block --num-cpus 2
          resources:
            requests:
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          #resources:
          #  requests:
          #    cpu: "2000m"
          #    memory: "4500Mi"
          #  limits:
          #    cpu: "2000m"
          #    memory: "4500Mi"
          volumeMounts:
            - name: hf-cache
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
            - name: blob-models
              mountPath: /models/llms
              readOnly: true
      volumes:
        - name: hf-cache
          emptyDir: {}
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi
        - name: blob-models
          persistentVolumeClaim:
            claimName: azure-blob-model-pvc
