apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azureblob-csi-sea-rw
provisioner: blob.csi.azure.com
parameters:
  containerName: models
  storageAccount: skamaljhuggingfacesea
  resourceGroup: azadmin
  protocol: fuse
mountOptions:
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - -o allow_other
  - -o rw
reclaimPolicy: Retain
volumeBindingMode: Immediate
